// <auto-generated>
// Code generated by LUISGen 7a834a15-de2d-4963-8f2e-a60f949355e3_v0.1.json -cs Luis.RestaurantLuis -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class RestaurantLuis: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            None, 
            RestaurantReservation_ChangeReservation, 
            RestaurantReservation_Confirm, 
            RestaurantReservation_DeleteReservation, 
            RestaurantReservation_FindReservationEntry, 
            RestaurantReservation_FindReservationWhen, 
            RestaurantReservation_FindReservationWhere, 
            RestaurantReservation_Reject, 
            RestaurantReservation_Reserve
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] RestaurantReservation_Address;
            public string[] RestaurantReservation_Cuisine;
            public string[] RestaurantReservation_NumberPeople;
            public string[] RestaurantReservation_PlaceName;
            public string[] RestaurantReservation_Rating;
            public string[] RestaurantReservation_Time;

            // Lists
            public string[][] RestaurantReservation_Atmosphere;
            public string[][] RestaurantReservation_MealType;

            // Instance
            public class _Instance
            {
                public InstanceData[] RestaurantReservation_Address;
                public InstanceData[] RestaurantReservation_Cuisine;
                public InstanceData[] RestaurantReservation_NumberPeople;
                public InstanceData[] RestaurantReservation_PlaceName;
                public InstanceData[] RestaurantReservation_Rating;
                public InstanceData[] RestaurantReservation_Time;
                public InstanceData[] RestaurantReservation_Atmosphere;
                public InstanceData[] RestaurantReservation_MealType;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<RestaurantLuis>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
